language: scala

env:
  global:
    - ADOPTOPENJDK=8
  matrix:
    - ADOPTOPENJDK=8
    - ADOPTOPENJDK=11

matrix:
  include:
    - scala: 2.11.12
      sudo: required
      before_install:
        # SDKMAN instruction is repeated
        # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
        - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
        - curl -sL https://get.sdkman.io | bash
        - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        # Scala Native
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      before_script:
        - sudo chmod +x /usr/local/bin/sbt
      script:
        - sbt ++${TRAVIS_SCALA_VERSION}! verifyNative/test
    - scala: 2.11.12
      sudo: required
      before_install:
        # SDKMAN instruction is repeated
        # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
        - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
        - curl -sL https://get.sdkman.io | bash
        - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        # Scala Native
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      before_script:
        - sudo chmod +x /usr/local/bin/sbt
      script:
        - sbt ++${TRAVIS_SCALA_VERSION}! verifyNative/test
      env: SCALANATIVE_VERSION="0.4.0-M2"

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version
  - javac -J-Xmx32m -version

script:
  - sbt ++2.11.12!    verifyJVM/test verifyJS/test
  - sbt ++2.12.10!    verifyJVM/test verifyJS/test
  - sbt ++2.13.1!     verifyJVM/test verifyJS/test
  - sbt ++0.19.0-RC1! verifyJVM/test

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
  - rm -rf $HOME/.ivy2/local

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.sbt
    - $HOME/.sdkman
